In [16]:
# 1
# What is a Python library? Why do we use Python libraries?
# A python library is a file. We can use the funcitons and classes of that file by including the library in our code.
# We use the Python libraries so that we can use the functions and classes of the Python libraries which are not in-built.

In [2]:
# 2
# What is the difference between Numpy array and List?
# Numpy array is used from Numpy library. Numpy library is written in C++ Language.
# Hence Numpy library is very fast compared to python lists.
# List consists of Heterogeneous data whereas numpy arrays consists of Homogeneous data.
# Lists stores the addresses of elements and not elements itself. On the other hand numpy arrays stores the elements itself.

In [3]:
# 3
import numpy as np
# 3. Find the shape, size and dimensions of the following array.
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"arr.size = {arr.size}")
print(f"arr.shape = {arr.shape}")
print(f"arr.size = {arr.ndim}")


arr.size = 12
arr.shape = (3, 4)
arr.size = 2


In [4]:
# 4
import numpy as np
# Write python code to access the first row of the following array?
# [[1, 2, 3, 4],
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Hello")
print(f"array's first row = {arr[0]}")

Hello
array's first row = [1 2 3 4]


In [5]:
# 5
import numpy as np
# How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4],
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"Element at 3rd Row and 4th Column is: {arr[2][3]}")

Element at 3rd Row and 4th Column is: 12


In [6]:
# 6
import numpy as np
# Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4],
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f"The odd indexed elements are:\n{arr[0:3,1::2]}")

The odd indexed elements are:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
# 7
# How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np
print(np.random.random_sample((3,3)))
print(np.random.rand(3,3))

[[0.808073   0.7464987  0.38074191]
 [0.8756146  0.66391734 0.05093614]
 [0.29816961 0.55295151 0.7096307 ]]
[[0.85615503 0.6098162  0.68177451]
 [0.95846441 0.04158703 0.41676111]
 [0.75933466 0.16729561 0.64742874]]


In [8]:
# 8
# Describe the difference between np.random.rand and np.random.randn?
# np.random.rand prints values betweeen 0-1 while np.random.randn can print any values between positive infinity to negative infinity.
# But the values generated are more likely to be closer to zero in the case of np.random.rand.

In [9]:
# 9
# Write code to increase the dimension of the following array? 
# [[1, 2, 3, 4],
# [5, 6, 7, 8], 
# [9, 10, 11, 12]] 
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Now we are expanding the array when axis = 0")
print(np.expand_dims(arr, axis = 0))
print()
print("Now we are expanding the array when axis = 1")
print(np.expand_dims(arr, axis = 1))

Now we are expanding the array when axis = 0
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

Now we are expanding the array when axis = 1
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [10]:
# 10
# 10. How to transpose the following array in NumPy? 
# [[1, 2, 3, 4] 
# [5, 6, 7, 8], 
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [11]:
# 11
# Consider the following matrix:
# Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python
# Perform the following operation using Python 
#  1. Index wise multiplication
#  2. Matrix multiplication 
#  3. Add both the matrix 
#  4. Subtract matrix B from A 
#  5. Divide Matrix B by A

import numpy as np
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13,14,15,16]])
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13,14,15,16]])
print(f"Indexwise Multiplication = \n {A * B}")
print(f"\nMatrix Multiplication = \n {A @ B}")
print(f"\nMatrix Addition = \n {A + B}")
print(f"\nMatrix Subtraction = \n {A - B}")
print(f"\nMatrix Division = \n {B / A}")

Indexwise Multiplication = 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]

Matrix Multiplication = 
 [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]

Matrix Addition = 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Matrix Subtraction = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# 12
# Which function in Numpy can be used to swap the byte order of an array?

In [13]:
# 13
# What is the significance of the np.linalg.inv function?

In [14]:
# 14
# What does the np.reshape function do, and how is it used?

import numpy as np
# The np.reshape() function in NumPy is used to change the shape (dimensions) of an array while keeping the same data.

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape the array into a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [15]:
# 15
# What is broadcasting in Numpy?
# Broadcasting in NumPy is a way to perform arithmetic operations (like addition, subtraction, multiplication, etc.)
# between arrays of different shapes without having to explicitly reshape them or use loops.
# Example
import numpy as np

arr = np.array([1, 2, 3, 4])
scalar = 10

result = arr + scalar
print(result)

[11 12 13 14]
